Let payment channels work
interledgerjs/ilp-plugin-ethereum pull request #8
Opened 2018-05-11 16:23 UTC by ukstv

2018-05-11 17:11 UTC, sharafian requested changes
Just a couple of small things, otherwise looks good

2018-05-11 17:11 UTC, sharafian commented on package.json
> +    "truffle-hdwallet-provider": "https://github.com/machinomy/truffle-hdwallet-provider"
Can we pin this to a specific commit, to prevent breaking updates in the future?

2018-05-11 17:11 UTC, sharafian commented on package.json
> +    "truffle-hdwallet-provider": "https://github.com/machinomy/truffle-hdwallet-provider"
Or you could publish it under your own NPM namespace and then use that here; Git dependencies can be buggy in the latest NPM version

2018-05-11 17:11 UTC, sharafian commented on test-infura-sell.js
> +        assetScale: 6
The scale of Wei should be 18. It's a little crazy so we may want to update it in the future to use something like MWei or GWei.

2018-05-11 17:11 UTC, sharafian commented on test.js
> +    assetScale: 6
see above comment on scale

2018-05-12 04:19 UTC, sharafian approved these changes

2018-05-12 04:23 UTC, ukstv commented
Fixed.

2018-05-14 09:13 UTC, ukstv commented
Yo buddy, is it good to be merged? @sharafian

2018-05-14 21:24 UTC, sharafian commented
Tried to merge from my mobile browser but it says there were conflicts. I'm flying in a couple hours but then I'll take a look

2018-05-15 11:35 UTC, ukstv commented
This branch has no conflicts with the base branch ¯ \ _ (ツ) _ / ¯

2018-05-16 14:54 UTC, merged